# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ancestor Journals
email: brycecaine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Journal entries of my ancestors and those of my family and relatives
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ancestorjournals.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Custom
authors:
- Ada Larsen
- Frederick Augustus Caine
